### ISSUE TITLE
Conditioned evaluation

### ISSUE THREAD

**Issue by GuyTevet** [korrawe/guided-motion-diffusion#11]
Hi again @korrawe !
Can you please help me map the conditioned metrics as reported in the paper (specifically: `Traj err`, `Loc err`, `Avg err`) to those reported in the eval script:

![image](https://github.com/korrawe/guided-motion-diffusion/assets/24757373/a7eafaac-f81c-418e-9a4d-347ab26ec321)

PS - `Traj diversity` seems to be missing (from `./save/unet_adazero_xl_x0_abs_proj10_fp16_clipwd_224/eval_humanml_cond_unet_adazero_xl_x0_abs_proj10_fp16_clipwd_224_000500000_gscale2.5_wo_mm.log`), how can I calculate it as well?

**Comment by korrawe** [comment]
Hi @GuyTevet,

For the first question, this eval is from the last row in Table 3 so here are the numbers in the paper:
![metrics](https://github.com/korrawe/guided-motion-diffusion/assets/13809460/01c912e0-9088-4985-ac96-b2a2f0576c40)

For the Traj diversity, you need to get the results from `'mm_short'`. In essence, we need to run with the same prompt multiple times in order to get the diversity within each prompt. This is what it looks like from the same setting:

> ==================== Replication 0 ====================
Time: 2023-03-07 19:21:43.095552
---> [ground truth] Matching Score: 2.9721
---> [ground truth] R_precision: (top 1): 0.5013 (top 2): 0.7039 (top 3): 0.7974 
---> [vald] Trajectory Error: (traj_fail_20cm): 0.5498 (traj_fail_50cm): 0.2988 (kps_fail_20cm): 0.2727 (kps_fail_50cm): 0.1158 (kps_mean_err(m)): 0.2731 
---> [vald] Skating Ratio: 0.1081
---> [vald] Matching Score: 5.6412
---> [vald] R_precision: (top 1): 0.3271 (top 2): 0.4775 (top 3): 0.5762 
Time: 2023-03-07 19:21:47.908423
---> [ground truth] FID: 0.0016
---> [vald] FID: 0.6460
Time: 2023-03-07 19:21:50.926160
---> [ground truth] Diversity: 9.8112
---> [vald] Diversity: 8.9611
Time: 2023-03-07 19:21:50.927105
**---> [vald] Trajectory Diversity: 0.2227**
---> [vald] Multimodality: 2.8109
!!! DONE !!!


Note that the `'mm_short'` is a smaller eval so we only take this number from the `'mm_short'` eval, other numbers are from the `'wo_mm'`.

**Comment by GuyTevet** [comment]
Thanks! Just to make sure I understand:

traj_fail_5ocm -> Traj err
kps_fail_50cm -> Loc. err
kps_mean_err -> Avg. err

**Comment by korrawe** [comment]
yes, that's correct

**Comment by GuyTevet** [comment]
Thanks again! Closing
