### ISSUE TITLE
Question about motion pre/postprocessing and format

### ISSUE THREAD

**Issue by billbai0102** [korrawe/guided-motion-diffusion#12]
I am trying to understand the code used in GMD, and one experiment I have done is (in the default unconditioned generation mode), I replace the model-generated motion with one of the existing motions in the dataset to visualize the motions in the dataset. Specifically, I am running this code in generate.py:

```
motion = torch.Tensor(np.load('./dataset/HumanML3D/new_joint_vecs_abs_3d/000036.npy')) // loads a 263-dim motion in the HumanML3D dataset
sample = [motion.unsqueeze(0).unsqueeze(1).repeat(10, 1, 1, 1).permute(0, 3, 1, 2) * 10] // reshapes the motion such that it can be processed by sample_to_motion
and then it proceeds to call sample_to_motion on this sample, and render it. 
```

However, when it renders the motion, the motion, while the joints are rotating and moving, the (x, y) position of the motion does not move at all, like the example below.

So my question is, what pre/post-processing goes into the motions after they are generated by the model (aside from std/mean adjustment and inverse random matrix proj)? And why does calling sample_to_motion on one of the existing files in the dataset produce a motion with no movement in the (x, y) direction? 

https://github.com/korrawe/guided-motion-diffusion/assets/31229051/c73280aa-5626-4f7b-9718-35f1fe52edd8

Thank you!

**Comment by billbai0102** [comment]
https://github.com/korrawe/guided-motion-diffusion/assets/31229051/5f9712dd-cf37-4573-ad59-3ce8075a1f61

For context, this is what the same motion looks like when it's rendered directly from the 22x3-dim motion. Why does the 263-dim motion not have any (x, y) movement, and even root rotation, like the original 22x3-dim motion?

**Comment by korrawe** [comment]
Hi @billbai0102,

Apart from the mean adjustment and projection, we did not do any other pre/post-processing.

As for your problem, it is probably because the 'abs_3d' flag is set incorrectly in the dataloader or args. The sample_to_motion takes this flag from 'args' and uses it [here](https://github.com/korrawe/guided-motion-diffusion/blob/c9d178d41f2d07e131869e64bcb612abc020f151/utils/output_util.py#L29). This function is used mainly when we produce motion from the model with 'abs_3d=True'. But, the data loader code is a bit messy so it might be difficult to catch this.

The wrong flag means that this function will use incorrect mean/std when converting the normalized vector back to motion. Only the first 4 values (x, z, rot, y) look wrong because the mean/std for other parts are the same regardless of 'abs_3d'.

Best,
Korrawe

**Comment by billbai0102** [comment]
Hi Korrawe,

I appreciate the extremely fast response!! Your advice was spot-on, and I've diagnosed the issue. Thank you - amazing work by the way!!
