### ISSUE TITLE
Loss becomes NaN when training GMD's UNet on HumanML3D with relative root representation

### ISSUE THREAD

**Issue by setarehc** [korrawe/guided-motion-diffusion#14]
Hi,

Thansk for the great work! I tried training the motion model with relative data and somewhere during training, I started getting NaN for the loss. To clarify, I'm interested in training GMD's motion model on the original relative representation of HumanM3D dataset. So, I set train_args to card.motion_rel_unet_adagn_xl in train_gmd.py. Note that I am able to train the motion model with absolute-root representation with no issues (when train_args=card.motion_abs_unet_adagn_xl). 
Have you faced a similar problem before? I'd appreciate any insights into how to address this issue.

Thanks,
Setareh

**Comment by korrawe** [comment]
Hi Setareh,

We also see the loss exploding sometimes when we train with the relative rep. The easiest way to solve this is to load the latest checkpoint and continue with a different seed. This solved our problem most of the time.

This usually only happens with relative training. I believe this is due to our UNET not very compatible with relative representation, but there is no concrete test on this.

Best,

**Comment by setarehc** [comment]
Thanks for the response! I'll give that a try :-)
