### ISSUE TITLE
Choice of mean and std for denormalizing absolute data in 'eval' mode

### ISSUE THREAD

**Issue by setarehc** [korrawe/guided-motion-diffusion#15]
Hi,

I'm looking at the evaluation code and I'm having a hard time understanding why the absolute data's mean and std are used to denormalize samples from gen_loader which have relative representation (if I understand correctly).
Specificly, in comp_v6_model_dataset.py line 481, gt_poses (sampled from gen_loader) is denormalized using self.dataset.std and self.dataset.mean which are equal to Std_abs_3d.npy and Mean_abs_3d.npy . Shouldn't self.dataset.std_rel and self.dataset.mean_rel be used instead? I tested denormalizing with both of these stats and then visualized the samples (after converting them back to global-xyz representation). The sample normalized with absolute data's mean and std looks better - it walks in a big circle where as the other motion appears to be walking in place with lots of sliding - but I'm not sure if I understand why.

Thanks,
Setareh

**Comment by korrawe** [comment]
Hi Setareh,

There are a few points that are intertwined here.

- First, the data's mean and std are loaded according to the model config. If the model is relative, the relative mean will be loaded. If the model is absolute, the absolute mean will be loaded
- `gen_loader` also loads the data according to the model config. **In our model, this is absolute.**
- If the visualized results are different from what you expect, the `abs_3d` flag is probably wrong somewhere.
- The difference between the abs_mean and rel_mean are only the first 3 values, (rot, x, z). If this is wrong, you will see the person walking in place.

Best,

**Comment by setarehc** [comment]
Thanks for the response. My model is absolute, and I can confirm that the absolute mean and std are set as default choices of mean and std for the dataset built according to the model config. However, it looks like when in `eval` mode, data is loaded from the relative dataset, even if `abs_3d` flag is set to true (refering to data_loaders.humanml.utils.get_opt.py lines 57-68):

```
if opt.dataset_name == 't2m':
        opt.data_root = './dataset/HumanML3D'
        # Set directory based on type of dataset representation:
        # Will load the original dataset (relative) if in 'eval' or 'gt' mode
        data_dir = 'new_joint_vecs_abs_3d' if use_abs3d and mode not in ['eval', 'gt'] else 'new_joint_vecs'
        if "DATA_ROOT" in os.environ:
            local_data_root = pjoin(os.environ["DATA_ROOT"], opt.data_root)
            opt.motion_dir = pjoin(local_data_root, data_dir)
            opt.text_dir = pjoin(local_data_root, 'texts')
        else:
            opt.motion_dir = pjoin(opt.data_root, data_dir)
            opt.text_dir = pjoin(opt.data_root, ['texts')
```

And in `comp_v6_model_dataset` I can see that samples from the absolute model are first converted to relative and then saved to be used for evaluation. So I was assuming that evaluator networks are trained on relative samples and thus both the generated samples and the ground-truth data (`gt_loader`) must be relative.

Please note that with the current code, I'm able to recreate your reported results. I'm just curious to understand what's happening :-)

**Comment by korrawe** [comment]
Yes, your understanding is correct. 
In eval mode, the relative dataset is loaded, but this relative dataset is not the same as in the MDM. There might be some confusion because we build on top of each other's code and my comments are not clear about it.

In summary, there are 3 version of the normalizations:

- The one from t2m. This is relative. It is used for evaluation when calculating FID because we use the distance of the encoded motion vectors according to t2m model. All motion generation paper will convert to using this mean for evaluating FID.
- The one from MDM. This is also relative. This is what used to train the MDM model which we based our data processing pipeline on. We modified this dataset to make it absolute
- Our GMD normalization. This is absolute. The difference to the MDM one is only on the first three values.

During evaluation, we need to undo the normalization, either with abs from MDM or rel from GMD, to an unnormalized version. Then, we will normalized again with t2m mean to evaluate the FID.

In the eval or gt mode, the dataset will be loaded with t2m mean. If you want to use other normalization, it needs to be in the train mode. I assume this is where the confusion comes from?

**Comment by setarehc** [comment]
Thanks for the clarification. I will close the issue :-)
