### ISSUE TITLE
Generating very long sequences

### ISSUE THREAD

**Issue by nghorbani** [korrawe/guided-motion-diffusion#18]
Hi, Thank you for sharing your work. I am interested to know if gdm could be used to generate very long motion sequences? say 1000 frames; e.g. a character running a trajectory for 1000 frames? I thought of using a sliding window but the speed during the blending section wont be consistent. 
I would appreciate any help.

**Comment by nghorbani** [comment]
https://github.com/priorMDM/priorMDM suggests a sequential composition with double take to ensure consistency. Could you imagine a combination of two works?

**Comment by korrawe** [comment]
Hi @nghorbani, yes, in principle, we should be able to generate very long sequences by out-painting from the existing output like in PriorMDM. Other methods like [DiffCollage](https://research.nvidia.com/labs/dir/diffcollage/) should also work.

The important thing for GMD specifically is we use absolute motion representation which assumes that we always start at the original facing -Z at the starting frame. So in order to outpaint, we will need to normalize the starting frame of the previous section to be at the origin first. Other than that I believe it will work.

**Comment by nghorbani** [comment]
does it make sense to make a proof of concept script?

**Comment by korrawe** [comment]
sure, you can start by checking how the normalization is done in [motion_representation.ipynb](https://github.com/korrawe/guided-motion-diffusion/blob/main/dataset/HumanML3D_abs/motion_representation.ipynb)
