### ISSUE TITLE
About the foot skating ratio of Real

### ISSUE THREAD

**Issue by gaogehan** [korrawe/guided-motion-diffusion#8]
Thanks foy your great work. I use your provided calculate_skating_ratio function to calculate the foot skating ratio of Real, the result is around 0.05. But The paper OmniControl reports that the foot skating ratio of Real is 0.00. Can you provide the calculation results of Real？

**Comment by gaogehan** [comment]
The foot skating ratio of MDM is consistent with the paper OmniControl.

**Comment by korrawe** [comment]
Based on the metrics reported, OmniControl seems to use our code for evaluation, although I do not know if they changed some details or not. If you call calculate_skating_ratio when evaluating the real dataset then the number you got is probably correct.

Realistically, this number cannot be 0.00 (from a motion with ~200 frames) because there will always be a frame where a foot moves more than 2.5cm near the ground (<5cm) such as before or after taking a step.

We might not be sure until OmniControl releases their code.

**Comment by ymingxie** [comment]
Hi @korrawe @hangaoge 

In OmniControl paper we didn't test the foot skating ratio of real actually. So 0.00 should be inaccurate and we will modify it in the next version. Thank you for pointing out @hangaoge 

We used [GMD code](https://github.com/korrawe/guided-motion-diffusion/blob/d4a38acf4256eac195741533e894a289d7a47c15/data_loaders/humanml/utils/metrics.py#L204) for the skating ratio evaluation without changing details. Thank you for your awesome code! @korrawe

**Comment by korrawe** [comment]
Hi @ymingxie 

Thank you for your quick response and clarification! Your results look great :)

Then, I will close this issue unless @hangaoge has more questions.

**Comment by gaogehan** [comment]
Thank you response @ymingxie @korrawe. My question has been resolved.
